[project]
name = "dynamodb-handler"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
  "aws-lambda-powertools[tracer]>=3.4.1,<4.0.0",
  "boto3>=1.36.2,<2.0.0",
]

[dependency-groups]
dev = [
  "ruff>=0.14.0,<0.15.0",
  "pyright>=1.1.379,<1.2.0",
  "types-aws-xray-sdk>=2.14.0.20240606,<2.16.0",
  "types-jmespath>=1.0.2.20240106,<1.1.0",
  "types-requests>=2.32.0.20241016,<2.34.0",
  "boto3-stubs>=1.36.5,<2.0.0",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 88
exclude = ["build", ".venv"]
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",  # flake8-annotations (ANN)
  "FBT",  # flake8-boolean-trap (FBT)
  # Keep copyright-header enforcement opt-in.
  "CPY",
  "EXE",  # flake8-executable (EXE)
  "FA",  # flake8-future-annotations (FA)
  "RET",  # flake8-return (RET)
  "B008",     # function-call-in-default-argument
  "A002",     # builtin-argument-shadowing
  "A004",     # builtin-import-shadowing
  "COM812",   # missing-trailing-comma
  "ISC001",   # single-line-implicit-string-concatenation
  "PIE790",   # unnecessary-placeholder
  "TRY003",   # raise-vanilla-args
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "strict"
exclude = ["build", ".venv"]
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"
